### ISSUE TITLE
Dependency endian_codec not included in the project

### ISSUE THREAD

**Issue by alejandropts1** [Slowerzs/PPLSystem#1]
Hello!! 

First of all nice research!! 

I saw you used a dependency endian_codec==0.1.2 but the last available version is 0.1.1 so i suppose you did modifications to it.
Could you include it in the project?? Using 0.1.1 it doesn't compile, we tried to modify it a little bit to solve the compilation issues but we encounter this error: 

`thread 'main' panicked at src/main.rs:83:9:
Could not find PID for rpcss or target PID is invalid
stack backtrace:
   0:           0x857c04 - std::backtrace_rs::backtrace::dbghelp64::trace::h697e746a0eb81098
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\..\..\backtrace\src\backtrace/dbghelp64.rs:99:5
   1:           0x857c04 - std::backtrace_rs::backtrace::trace_unsynchronized::h8bcac2bc6f0067ef
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\..\..\backtrace\src\backtrace/mod.rs:66:5
   2:           0x857c04 - std::sys_common::backtrace::_print_fmt::h1d525f05694e29c0
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\sys_common/backtrace.rs:68:5
   3:           0x857c04 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd33bdb7f4932788b
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\sys_common/backtrace.rs:44:22
   4:           0x8a615b - core::fmt::rt::Argument::fmt::hbcd44ab1cf7c2ab6
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\fmt/rt.rs:142:9
   5:           0x8a615b - core::fmt::write::h88ba2385290d659c
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\fmt/mod.rs:1153:17
   6:           0x84e18d - std::io::Write::write_fmt::h4096e092b1acc2d9
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\io/mod.rs:1843:15
   7:           0x8579fe - std::sys_common::backtrace::_print::h94a648d141efa937
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\sys_common/backtrace.rs:47:5
   8:           0x8579fe - std::sys_common::backtrace::print::h7ce8dec1748238b0
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\sys_common/backtrace.rs:34:9
   9:           0x85a77f - std::panicking::default_hook::{{closure}}::h43877b65ce5100bf
  10:           0x85a43c - std::panicking::default_hook::h40178e9ee41c4d12
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src/panicking.rs:292:9
  11:           0x85ae92 - std::panicking::rust_panic_with_hook::he36247ac76102f03
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src/panicking.rs:779:13
  12:           0x85ad11 - std::panicking::begin_panic_handler::{{closure}}::h06edfffae4444bfe
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src/panicking.rs:649:13
  13:           0x858389 - std::sys_common::backtrace::__rust_end_short_backtrace::hdc2e619c8d1ebac1
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\sys_common/backtrace.rs:171:18
  14:           0x85aa76 - rust_begin_unwind
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src/panicking.rs:645:5
  15:           0x8a2557 - core::panicking::panic_fmt::he2608bd87643dbc4
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src/panicking.rs:72:14
  16:           0x106703 - pplsystem::main::h547be70e2e2fb7cc
  17:           0x115356 - std::sys_common::backtrace::__rust_begin_short_backtrace::h627cb3703a1f43e9
  18:           0x1123bc - std::rt::lang_start::{{closure}}::h1f3a369d7130c4f3
  19:           0x841202 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hadeee22bac610ada
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\ops/function.rs:284:13
  20:           0x841202 - std::panicking::try::do_call::hec2a140754dda19b
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src/panicking.rs:552:40
  21:           0x841202 - std::panicking::try::h7f975b58f5c71251
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src/panicking.rs:516:19
  22:           0x841202 - std::panic::catch_unwind::h0ebf513cbfaadc93
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src/panic.rs:146:14
  23:           0x841202 - std::rt::lang_start_internal::{{closure}}::hf1cd4462e65ae8a9
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src/rt.rs:148:48
  24:           0x841202 - std::panicking::try::do_call::h382503ad6696e9cf
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src/panicking.rs:552:40
  25:           0x841202 - std::panicking::try::hf72ca2e8b71e7690
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src/panicking.rs:516:19
  26:           0x841202 - std::panic::catch_unwind::he9be8c592ad3debf
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src/panic.rs:146:14
  27:           0x841202 - std::rt::lang_start_internal::h513f1e1ee7f27549
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src/rt.rs:148:20
  28:           0x1092cd - main
  29:           0x1013b4 - __tmainCRTStartup
                               at ./build/x86_64-w64-mingw32-x86_64-w64-mingw32-crt/./mingw-w64-crt/crt/crtexe.c:339:15
  30:           0x10150b - mainCRTStartup
                               at ./build/x86_64-w64-mingw32-x86_64-w64-mingw32-crt/./mingw-w64-crt/crt/crtexe.c:223:9
  31:     0x7ffa5cc1257d - <unknown>
  32:     0x7ffa5e7aaa48 - <unknown>`

**Comment by Slowerzs** [comment]
I completely forgot about it, thank you for reminding me! I have added it to the repository, this should compile fine now :)

**Comment by alejandropts1** [comment]
Thaaanks!! Nice job!! Very nice technique :)
