### ISSUE TITLE
Error locating the COM secret and context

### ISSUE THREAD

**Issue by cookpoo78** [Slowerzs/PPLSystem#2]
Tried on multiple PPL processes including Services.exe and MsMpEng.exe, on my main laptop machine (also on non-PPL processes), doesn't work 😕
I cross-compiled from Linux, maybe this is the reason?

C:\Users\<SNIP>\Desktop> .\pplsystem.exe --dll C:\Users\<SNIP>\Desktop\DllMain.dll --pid 1044 --dump c:\hi.temp
[+] OID Server list addr: 0x283172561D0
[+] Number of entries : 0x400
[+] OXID Array @ 0x283172C3F20
thread 'main' panicked at src/main.rs:213:9:
[-] Failed finding IPID or OXID for IRundown in target process. This is most likely due to the process not having initialized COM.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
C:\Users\<SNIP>\Desktop> .\pplsystem.exe --dll C:\Users\<SNIP>\Desktop\DllMain.dll --pid 1016 --dump c:\hi.temp
[+] OID Server list addr: 0x283172561D0
[+] Number of entries : 0x400
[+] OXID Array @ 0x283172C3F20
thread 'main' panicked at src/main.rs:213:9:
[-] Failed finding IPID or OXID for IRundown in target process. This is most likely due to the process not having initialized COM.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
C:\Users\<SNIP>\Desktop> .\pplsystem.exe --dll C:\Users\<SNIP>\Desktop\DllMain.dll --pid 14900 --dump c:\hi.temp
[+] OID Server list addr: 0x283172561D0
[+] Number of entries : 0x400
[+] OXID Array @ 0x283172C3F20
[+] Found : PID - 14900
[+] Found : OXID - 0x70D2BF5772F303C1
[+] Found : IPID - 01CC0000-343A-FFFF-8FC9-325DC3B2BD19
thread 'main' panicked at src/main.rs:216:71:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
C:\Users\<SNIP>\Desktop> .\pplsystem.exe --dll C:\Users\<SNIP>\Desktop\DllMain.dll --pid 4140 --dump c:\hi.temp
[+] OID Server list addr: 0x283172561D0
[+] Number of entries : 0x400
[+] OXID Array @ 0x283172C3F20
[+] Found : PID - 4140
[+] Found : OXID - 0x324CF63DB4959786
[+] Found : IPID - 009C0000-2C10-0000-97E4-FD1AD3890ED5
thread 'main' panicked at src/main.rs:216:71:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Slowerzs** [comment]
Hello !
I haven't faced this issue before, where apparently the program fails to locate the offsets of either the COM process secret or context.
I've added a fallback for locating these using symbols in bfc7831c52ba6d87bc937e2f142effa773b5a495, which should be more robust :)
